create table tab_events (
    id bigint generated by default as identity primary key,
    name varchar(100) not null,
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp,
    constraint uk_events_name unique (name)
);

create table tab_gift_status (
    id bigint generated by default as identity primary key,
    name varchar(100) not null,
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp,
    constraint uk_gift_status_name unique (name)
);

insert into tab_events (name)
values
    ('NONE'),
    ('BIRTHDAY'),
    ('CHRISTMAS'),
    ('MARRIAGE');

insert into tab_gift_status (name)
values
    ('IDEA'),
    ('PURCHASED'),
    ('DELIVERED');

alter table tab_gifts add column event_id bigint;
alter table tab_gifts add column status_id bigint;

update tab_gifts gifts
set event_id = events.id
from tab_events events
where gifts.event = events.name;

update tab_gifts gifts
set status_id = gift_status.id
from tab_gift_status gift_status
where gifts.status = gift_status.name;

alter table tab_gifts alter column event_id set not null;
alter table tab_gifts alter column status_id set not null;

alter table tab_gifts add constraint fk_gifts_event_id foreign key (event_id) references tab_events(id);
alter table tab_gifts add constraint fk_gifts_status_id foreign key (status_id) references tab_gift_status(id);

alter table tab_gifts drop column event;
alter table tab_gifts drop column status;
