create table tab_shopping_list (
    id bigint generated by default as identity primary key,
    title varchar(40) not null,
    created_at timestamp with time zone default current_timestamp,
    updated_at timestamp with time zone default current_timestamp
);

alter table tab_shopping_items
add column list_id bigint;

alter table tab_shopping_items
add constraint fk_shopping_list_id foreign key (list_id) references tab_shopping_list(id);