create table tab_gift_list (
    id bigint generated by default as identity primary key,
    title varchar(40) not null,
    created_at timestamp with time zone default current_timestamp,
    updated_at timestamp with time zone default current_timestamp
);

alter table tab_gifts
add column list_id bigint;

alter table tab_gifts
add constraint fk_gifts_list_id foreign key (list_id) references tab_gift_list(id);